LongxingTan/open-retrievals

- .readthedocs.yml
> fix(docs): readthedocs.yml

- .readthedocs.yml
> fix(docs): docs py version

- .github/workflows/test.yml
> fix(codeql): update the codeql version

- .github/workflows/test.yml
- .gitignore
- README.md
- src/retrievals/models/match_auto.py
> fix: update automatch

- src/retrievals/models/match_auto.py
> fix: match auto

- examples/rag_langchain.py
- src/retrievals/models/embedding_auto.py
- src/retrievals/models/rag.py
- src/retrievals/tools/__init__.py
- src/retrievals/tools/corpus_processor.py
- src/retrievals/tools/langchain.py
- tests/test_models/test_embedding_auto.py
> feat: add the rag example  @LongxingTan

- README.md
- docs/source/rag.rst
- src/retrievals/data/__init__.py
- src/retrievals/data/dataset.py
- src/retrievals/losses/bpr.py
- src/retrievals/losses/dice.py
- src/retrievals/losses/margin_mse.py
- src/retrievals/losses/pearson_loss.py
- src/retrievals/metrics/mrr.py
- src/retrievals/models/pooling.py
- src/retrievals/models/rerank.py
> docs: update

- src/retrievals/models/rag.py
- src/retrievals/models/rerank.py
- tests/test_losses/test_infonce.py
> fix: update rag

- README.md
- docs/source/rag.rst
> docs: update docs

- src/retrievals/models/rerank.py
- src/retrievals/version.py
> feat: uppate rerank output

- README.md
- README_zh-CN.md
- examples/finetune_llm_embed.py
- examples/finetune_pairwise_embed.py
- examples/rerank_cross_encoder.py
- src/retrievals/data/collator.py
- src/retrievals/data/dataset.py
- src/retrievals/losses/cosine_similarity.py
- src/retrievals/models/embedding_auto.py
- src/retrievals/models/rerank.py
- src/retrievals/models/retrieval_auto.py
- src/retrievals/trainer/custom_trainer.py
- tests/test_losses/test_cosine_similarity.py
> fix: rename passage to document

- src/retrievals/losses/simcse.py
- src/retrievals/models/rerank.py
- src/retrievals/models/retrieval_auto.py
- src/retrievals/trainer/trainer.py
> fix: rerank trainer and model

- examples/rerank_cross_encoder.py
- src/retrievals/models/rerank.py
- src/retrievals/trainer/trainer.py
> fix: rerank examples

- examples/README.md
- examples/finetune_pairwise.sh
> docs: update example doc

- README.md
- README_zh-CN.md
- src/retrievals/data/collator.py
- src/retrievals/data/dataset.py
- src/retrievals/models/embedding_auto.py
- src/retrievals/models/retrieval_auto.py
- src/retrievals/trainer/custom_trainer.py
- src/retrievals/trainer/trainer.py
- src/retrievals/version.py
- tests/test_data/test_collator.py
> fix: custom trainer and readme

- README.md
- README_zh-CN.md
- examples/rag_langchain.py
- examples/retrieval_faiss.py
- src/retrievals/tools/__init__.py
- src/retrievals/tools/langchain.py
> fix: langchain rerank example

- README_ja-JP.md
I created Japanese translated README.
> docs: Add Japanese README

- src/retrievals/data/collator.py
- src/retrievals/data/dataset.py
- src/retrievals/data/sampler.py
- src/retrievals/losses/infonce.py
- src/retrievals/models/embedding_auto.py
- src/retrievals/models/rerank.py
- src/retrievals/models/utils.py
- src/retrievals/tools/langchain.py
- src/retrievals/trainer/custom_trainer.py
- src/retrievals/trainer/trainer.py
> fix: langchain integration rerank

- README.md
- README_ja-JP.md
- README_zh-CN.md
> docs: update readme

- README.md
- README_ja-JP.md
- README_zh-CN.md
- src/retrievals/models/embedding_auto.py
- src/retrievals/models/rerank.py
- src/retrievals/models/utils.py
- src/retrievals/trainer/custom_trainer.py
> fix: basic examples smooth run

- .github/workflows/test.yml
- src/retrievals/__init__.py
- src/retrievals/data/collator.py
- src/retrievals/data/dataset.py
- src/retrievals/models/embedding_auto.py
- src/retrievals/models/rerank.py
- src/retrievals/pipelines/rerank.py
- src/retrievals/tools/file_parser.py
- src/retrievals/version.py
> fix: rerank benchmark

- README.md
- README_ja-JP.md
- README_zh-CN.md
- docs/source/embed.rst
- docs/source/index.rst
- docs/source/quick-start.rst
- docs/source/rag.rst
- docs/source/rerank.rst
- src/retrievals/data/collator.py
- src/retrievals/data/dataset.py
- src/retrievals/losses/__init__.py
- src/retrievals/losses/colbert_loss.py
- src/retrievals/models/rerank.py
- src/retrievals/models/retrieval_auto.py
- src/retrievals/pipelines/embed.py
- src/retrievals/pipelines/rag.py
- src/retrievals/pipelines/rerank.py
- src/retrievals/tools/file_parser.py
- src/retrievals/tools/generator.py
- src/retrievals/tools/langchain.py
- src/retrievals/tools/llama_index.py
- src/retrievals/tools/promptor.py
- src/retrievals/tools/rewriter.py
- src/retrievals/trainer/adversarial.py
- src/retrievals/trainer/custom_trainer.py
- src/retrievals/trainer/trainer.py
- src/retrievals/version.py
- tests/test_trainer/test_adversarial.py
> fix: rag benchmark

- README.md
- docs/source/embed.rst
- docs/source/index.rst
- docs/source/rerank.rst
- docs/source/retrieval.rst
- examples/1_retrieval/llm_for_embed/llm_finetune_for_embed.py
- src/retrievals/data/collator.py
- src/retrievals/models/embedding_auto.py
- src/retrievals/models/rerank.py
- src/retrievals/models/retrieval_auto.py
- src/retrievals/trainer/custom_trainer.py
- src/retrievals/version.py
- tests/test_trainer/test_custom_trainer.py
- tests/test_trainer/test_trainer.py
> tests: add custom trainer test

- README_zh-CN.md
- docs/source/rag.rst
- examples/1_retrieval/pairwise_finetune.py
- examples/2_rerank/train_colbert.py
- examples/README.md
- requirements.txt
- src/retrievals/__init__.py
- src/retrievals/data/collator.py
- src/retrievals/data/dataset.py
- src/retrievals/losses/colbert_loss.py
- src/retrievals/models/embedding_auto.py
- src/retrievals/models/pooling.py
- src/retrievals/models/rerank.py
- src/retrievals/models/retrieval_auto.py
- src/retrievals/pipelines/__init__.py
- src/retrievals/pipelines/embed.py
- src/retrievals/pipelines/rag.py
- src/retrievals/pipelines/rerank.py
- src/retrievals/trainer/trainer.py
- src/retrievals/version.py
- tests/test_data/test_dataset.py
> fix: retrievals pipeline import

- README.md
- README_ja-JP.md
- README_zh-CN.md
- examples/README.md
- src/retrievals/data/dataset.py
- src/retrievals/losses/colbert_loss.py
- src/retrievals/losses/infonce.py
- src/retrievals/losses/pair_kl.py
- src/retrievals/losses/token_loss.py
- src/retrievals/models/base.py
- src/retrievals/models/embedding_auto.py
- src/retrievals/models/rerank.py
- src/retrievals/pipelines/embed.py
- src/retrievals/pipelines/rerank.py
- src/retrievals/trainer/trainer.py
- tests/test_losses/test_colbert_loss.py
- tests/test_losses/test_infonce.py
- tests/test_losses/test_token_loss.py
- tests/test_models/test_embedding_auto.py
> fix: embed and rerank benchmark

- .github/workflows/test.yml
- README.md
- README_ja-JP.md
- README_zh-CN.md
- docs/source/embed.rst
- docs/source/index.rst
- docs/source/quick-start.rst
- docs/source/rerank.rst
- docs/source/retrieval.rst
- examples/README.md
- examples/rerank_colbert.py
- examples/rerank_cross_encoder.py
- examples/t2_ranking/rerank_colbert.sh
- src/retrievals/data/dataset.py
- src/retrievals/data/synthesis.py
- src/retrievals/losses/colbert_loss.py
- src/retrievals/models/base.py
- src/retrievals/models/embedding_auto.py
- src/retrievals/models/rerank.py
- src/retrievals/pipelines/embed.py
- src/retrievals/pipelines/llm.py
- src/retrievals/pipelines/rerank.py
- tests/test_losses/test_colbert_loss.py
- tests/test_models/test_rerank.py
> feat: colbert from pretrained colbert like bge-m3

- README.md
- README_ja-JP.md
- README_zh-CN.md
- docs/source/embed.rst
- docs/source/index.rst
- docs/source/quick-start.rst
- docs/source/rerank.rst
- examples/0_embedding/README.md
- examples/0_embedding/train_llm.py
- examples/0_embedding/train_pairwise.py
- examples/2_reranking/train_llm.py
- examples/README.md
- examples/README_zh_CN.md
- src/retrievals/tools/langchain.py
> docs: update the fine-tuning examples

- README.md
- README_ja-JP.md
- README_zh-CN.md
- docs/source/embed.rst
- docs/source/quick-start.rst
- examples/0_embedding/README.md
- examples/0_embedding/train_llm.py
- examples/0_embedding/train_pairwise.py
- examples/eval/eval_retrieval2.py
- src/retrievals/__init__.py
- src/retrievals/data/__init__.py
- src/retrievals/data/collator.py
- src/retrievals/pipelines/embed.py
- src/retrievals/trainer/trainer.py
- tests/test_data/test_collator.py
- tests/test_trainer/test_trainer.py
> refactor: combine collator for pair and triplet
